/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    eclipse
    `java-library`
    id("org.jetbrains.dokka") version "1.9.20"
    `maven-publish`
    `project-report`
}

repositories {
    mavenCentral()
    mavenLocal() // This is to access the local Maven repository.
}

dependencies {
    implementation(project(":jact-core"))

    // for testing    
    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.testcontainers:junit-jupiter:1.19.3")
    testImplementation("org.testcontainers:localstack:1.19.3")
    
    // common libraries
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.20.0")
    implementation("com.google.guava:guava:33.2.0-jre")

    // sqs
    implementation(platform("software.amazon.awssdk:bom:2.21.1"))
    implementation("software.amazon.awssdk:sqs")
}

group = "com.metatrope"
version = "0.0.1"
description = "jact-sqs"
java.sourceCompatibility = JavaVersion.VERSION_21

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

subprojects {
    apply(plugin = "org.jetbrains.dokka")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

configurations {
    create("scm")
}

